---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s-reloader
  annotations:
    reloader.stakater.com/auto: "true"
type: Opaque
data:
  POSTGRES_PASSWORD: azhzcGFzc3dvcmQK=
